### ISSUE TITLE
Нет зеленой кнопки автотеста

### ISSUE THREAD

**Issue by TemPoun** [kiray-gd/nmocrasher#1]
Нет зеленой кнопки автотеста.Сделал все по гайду не помогает

**Comment by TemPoun** [comment]
Ответь пожалуйста срочно нужно

**Comment by RazboinikMax** [comment]
Кнопка появилась, но скрипт не работает на chrome

**Comment by kiray-gd** [comment]
Если есть кнопка, но не запускается скрипт, у вас возможно маленький монитор и скрипт не видит "название" темы теста. Прежде, чем нажать "Включить автотест" - нажмите кнопку "Развернуть" (она должна находится ровно под зеленой кнопкой - "Включить автотест")

**Comment by kiray-gd** [comment]
Иначе же, возможно просто ответов на тест в 24forcare - нет (или они криво выложены)
