### ISSUE TITLE
.

### ISSUE THREAD

**Issue by 14karat14444** [kiray-gd/nmocrasher#10]
> У вас тоже скипает вопросы? UPD: Решил.
как решил подскажи

_Originally posted by @14karat14444 in https://github.com/kiray-gd/nmocrasher/issues/9#issuecomment-2438020220_

**Comment by Friendly595** [comment]
Дайте Ваши контакты, подскажу.

**Comment by 14karat14444** [comment]
> Дайте Ваши контакты, подскажу.

@Karatvin в телеграмме напишите незнайка на аватарке. а там может в вотсап перейдем

**Comment by 14karat14444** [comment]
> Дайте Ваши контакты, подскажу.

@Karatvin   в телеграмме ннапишите незнайка на аватаре

**Comment by Friendly595** [comment]
> > Дайте Ваши контакты, подскажу.
> 
> @Karatvin в телеграмме ннапишите незнайка на аватаре

Написал.

**Comment by Levin-crk** [comment]
> > > Дайте Ваши контакты, подскажу.
> 
> > 
> 
> > @Karatvin в телеграмме ннапишите незнайка на аватаре
> 
> 
> 
> Написал.

Привет , напиши сюда пожалуйста @levinchik это мой тг , я незнаю как решить проблемы , помоги пожалуйста)
