### ISSUE TITLE
Помогите пожалуйста ;( , скипает вопросы , не вставляет , что делать ?

### ISSUE THREAD

**Issue by Levin-crk** [kiray-gd/nmocrasher#11]
Помогите пожалуйста ;( , скипает вопросы , не вставляет , что делать ?

**Comment by Levsha-Sl** [comment]
Могу помочь

**Comment by Levsha-Sl** [comment]
@Levin-crk Есть решение на текущий момент работает

**Comment by wrenay09** [comment]
@Levsha-Sl помогите, пожалуйста, такая же проблема
тг @Wrenay
