### ISSUE TITLE
Появились случаю блокировки на портале нмо, предложение по улучшению

### ISSUE THREAD

**Issue by ilyaakrickij** [kiray-gd/nmocrasher#12]
Разработчик расширения для браузера для решения тестов предупредил о блокировках на портале нмо, думаю, что не с проста он об этом предупредил. Поэтому предлагаю вам добавить рандомную задержку не большую, но адекватную для ответа на вопрос, так же в описании проекта подсветить момент, чтобы за раз не решали слишком много)

**Comment by MaximMedik** [comment]
У меня пропала кнопка "решать", похоже....закрылась лавочка....🤔

**Comment by ilyaakrickij** [comment]
> У меня пропала кнопка "решать", похоже....закрылась лавочка....🤔

А сколько тестов в день решали?

**Comment by MaximMedik** [comment]
> > У меня пропала кнопка "решать", похоже....закрылась лавочка....🤔
> 
> А сколько тестов в день решали?

По разному, 30-50.
P s кнопка именно скриптовая, на НМО все ок, иом'ы открываются

**Comment by ilyaakrickij** [comment]
> > > У меня пропала кнопка "решать", похоже....закрылась лавочка....🤔
> > 
> > 
> > А сколько тестов в день решали?
> 
> По разному, 30-50

Понял, столько в день значит не решаю :D

**Comment by MaximMedik** [comment]
> > > > У меня пропала кнопка "решать", похоже....закрылась лавочка....🤔
> > > 
> > > 
> > > А сколько тестов в день решали?
> > 
> > 
> > По разному, 30-50
> 
> Понял, столько в день значит не решаю :D

А не , все норм. Единственное НМО опять тупит и в план не даёт добавить, что то похоже снова мутят....

**Comment by Levsha-Sl** [comment]
@kiray-gd в программе есть момент с циклом в цикле в котором нет задержки и программа совершает N² действий и задержка происходит только через N итераций.. человек так делать не будет, надо цикл к N итераций свести и задержку туда вставить, я не работаю с JS пытался исправить, но тогда программа только один ответ из нескольких выдавала

**Comment by Serega007RU** [comment]
> нет задержки

нет ещё и координат, а то они теперь и координаты проверяют где ты кликнул, скрипт же использует метод click который не передаёт координаты
