### ISSUE TITLE
Не работает:(

### ISSUE THREAD

**Issue by RazboinikMax** [kiray-gd/nmocrasher#2]
Обновите скрипт, все перепробывал. может из за того что версия tampermonkey вышла

**Comment by kiray-gd** [comment]
Проверил, работает на сторонней машине. Однако обнаружил, что Mozilla Firefox теперь не поддерживает скрипт. Решение обнаруженных возможных проблем описал в readme

**Comment by RazboinikMax** [comment]
Подскажите пожалуйста, браузер chrome и tampermonkey 5.2.3, при сохранение скрипта main.js в tampermonkey,  окошко не выходит (для ввода сайта 24forcare.com) при входе на сайт [edu](https://nmfo-vo.edu.rosminzdrav.ru/) и при первом запуске программы (tampermonkey), скрипт не запрашивает доступ. Режим разработчика включен. Что может быть?

**Comment by kiray-gd** [comment]
> Подскажите пожалуйста, браузер chrome и tampermonkey 5.2.3, при сохранение скрипта main.js в tampermonkey, окошко не выходит (для ввода сайта 24forcare.com) при входе на сайт [edu](https://nmfo-vo.edu.rosminzdrav.ru/) и при первом запуске программы (tampermonkey), скрипт не запрашивает доступ. Режим разработчика включен. Что может быть?

В новой версии программы, "окошко" выходить и не должно, скрипт сейчас сам находит сайт.
Оставьте дискорд для связи, попробуем разобраться

**Comment by RazboinikMax** [comment]
Спасибо, нашел решение!!!:) после включения кнопки "включить автотест" если ни чего не происходит, то нужно обновить страницу на F5, а дальше сприпт заработает
