### ISSUE TITLE
не ищет тесты с годом

### ISSUE THREAD

**Issue by borinya** [kiray-gd/nmocrasher#3]
привет!
классная реализация, знакомые врачи очень благодарны
проходить по 100+ тестов - форменное издевательство с учетом качества сайта 
обнаружил следующую ситуацию
скрипт ищет полное название, а на сайте НМО некоторые названия с годами
пример
«Отморожение. Гипотермия. Другие эффекты
воздействия низкой температуры (по
утвержденным клиническим рекомендациям)-
2021» - полное название теста на НМО
но есть ответы на сайте для теста "Отморожение. Гипотермия. Другие эффекты воздействия низкой температуры (по утвержденным клиническим рекомендациям)" - без года, тире и лишних пробелов

**Comment by kiray-gd** [comment]
Понятно. В свободное время повикшу, спасибо.

**Comment by Leroy30rus** [comment]
привет, как с тобой связаться? У меня не получается запустить, вроде все делаю по инструкции, а на сайте скрипт отказывается запускаться.....
![Скриншот 15-08-2024 160218](https://github.com/user-attachments/assets/6577e4fc-a86a-4de8-af1d-dfc63c34439c)
![Скриншот 15-08-2024 160335](https://github.com/user-attachments/assets/b1e31b30-38ec-4d70-babf-3355a9272860)

**Comment by kiray-gd** [comment]
> привет, как с тобой связаться? У меня не получается запустить, вроде все делаю по инструкции, а на сайте скрипт отказывается запускаться..... ![Скриншот 15-08-2024 160218](https://private-user-images.githubusercontent.com/178479421/358213204-6577e4fc-a86a-4de8-af1d-dfc63c34439c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODQ4NDgsIm5iZiI6MTcyMzg4NDU0OCwicGF0aCI6Ii8xNzg0Nzk0MjEvMzU4MjEzMjA0LTY1NzdlNGZjLWE4NmEtNGRlOC1hZjFkLWRmYzYzYzM0NDM5Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwODQ5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTc1MWMwNjI2NDE4ZDIxOGEzMTY4MTdjYzY0MTNjMjQzYmZmNGEzNmI2NTU2NTljOWI0NTA4NWQ5MjA5ZDM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TERXlGU2ZS1KtRFTuAOLmosA30-DvplvAaERkzCR_80) ![Скриншот 15-08-2024 160335](https://private-user-images.githubusercontent.com/178479421/358213216-b1e31b30-38ec-4d70-babf-3355a9272860.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODQ4NDgsIm5iZiI6MTcyMzg4NDU0OCwicGF0aCI6Ii8xNzg0Nzk0MjEvMzU4MjEzMjE2LWIxZTMxYjMwLTM4ZWMtNGQ3MC1iYWJmLTMzNTVhOTI3Mjg2MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwODQ5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTg5ZDBjOGUyOGMzMzI5OGFlMGQzYjVjYTA5NWRlMmI3OTcwNWNmN2ZjMDA3OTI1NTYyNzYwYWMwZDg1MDRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CwSHsM-StWjw0EFkm-Mz5HJMTAYTEED6Xr6paTNexcM)

Замените в скрипте некоторые строчки, а именно..
содержимое строчки 7
`// @match        https://iomqt-vo.edu.rosminzdrav.ru/*`
на
`// @match        https://iomqt-spo.edu.rosminzdrav.ru/*`

содержимое строчки 124 
` if (window.location.hostname === 'iomqt-vo.edu.rosminzdrav.ru') {`
на это
` if (window.location.hostname === 'iomqt-spo.edu.rosminzdrav.ru') {`

**Comment by kiray-gd** [comment]
> привет! классная реализация, знакомые врачи очень благодарны проходить по 100+ тестов - форменное издевательство с учетом качества сайта обнаружил следующую ситуацию скрипт ищет полное название, а на сайте НМО некоторые названия с годами пример «Отморожение. Гипотермия. Другие эффекты воздействия низкой температуры (по утвержденным клиническим рекомендациям)- 2021» - полное название теста на НМО но есть ответы на сайте для теста "Отморожение. Гипотермия. Другие эффекты воздействия низкой температуры (по утвержденным клиническим рекомендациям)" - без года, тире и лишних пробелов

Пофиксил

**Comment by kiray-gd** [comment]
> привет, как с тобой связаться? У меня не получается запустить, вроде все делаю по инструкции, а на сайте скрипт отказывается запускаться..... ![Скриншот 15-08-2024 160218](https://private-user-images.githubusercontent.com/178479421/358213204-6577e4fc-a86a-4de8-af1d-dfc63c34439c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODkwNzYsIm5iZiI6MTcyMzg4ODc3NiwicGF0aCI6Ii8xNzg0Nzk0MjEvMzU4MjEzMjA0LTY1NzdlNGZjLWE4NmEtNGRlOC1hZjFkLWRmYzYzYzM0NDM5Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwOTU5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODJhNjMzZGUxMzNiNGJkMzM5OGI0M2ZhYjdiNDAwYjIyYzUxNzE0ZmRiZGRmMDY3ZGViNmJlOGUzM2M2NGNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GcPkSPItMkqoXaG1xvD8ySleEcrMb8IYGk-4-KOFg_8) ![Скриншот 15-08-2024 160335](https://private-user-images.githubusercontent.com/178479421/358213216-b1e31b30-38ec-4d70-babf-3355a9272860.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODkwNzYsIm5iZiI6MTcyMzg4ODc3NiwicGF0aCI6Ii8xNzg0Nzk0MjEvMzU4MjEzMjE2LWIxZTMxYjMwLTM4ZWMtNGQ3MC1iYWJmLTMzNTVhOTI3Mjg2MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwOTU5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTRmZTE2MDUxZTA5YzQxMmQyMWMyZDdkZGRhMjk5MTY1YzhiZmM4NWIwYWYwODM3YzUxYTA2N2NhNDlkOGY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DLE0LHAmo67gNYtHnFRt3hj4AR251rG4k1eHID2oKTE)

Добавил возможность работы скрипта на всех поддоменах edu.rosminzdrav
