### ISSUE TITLE
Ответы загружены но не вбиваются

### ISSUE THREAD

**Issue by Levsha-Sl** [kiray-gd/nmocrasher#4]
Ответы загружены в массив, но не вбиваются, программа просто перелистывает ответы

**Comment by Friendly595** [comment]
Тоже самое, дело не в браузере, вероятно структуру затронули сайта и скрипт перестал искать ответы в тесте, мой скрипт тоже перестал работать, поэтому жду скорее фикс крашера.

**Comment by Levsha-Sl** [comment]
> вероятно структуру затронули сайта

окей попробую глянуть скрипт как он работает

**Comment by Levsha-Sl** [comment]
Мне кажется проблема с поиском вопроса в массиве, стр 205 функция findAnswer

**Comment by Friendly595** [comment]
Я предполагаю, что проблема с поиском как раз таки ответов на сайте НМО, ибо у меня вопрос находит.

**Comment by Levsha-Sl** [comment]
@Friendly595 покажите ваш код? Я использую стандартный код с этого репозитория, в консоль у меня выходит найденный вопрос и доступные варианты ответов, так же этот вопрос реально самостоятельно найти в полученном массиве и глянуть ответ на него.

Не могу заметить отличий в текстовом выводе. Может они заменили буквы "С" на английский)

**Comment by Levsha-Sl** [comment]
@Friendly595 я проверил они меняют алфавит букв 
![IMG20240822172013](https://github.com/user-attachments/assets/2806a46f-98ab-4390-9815-d5d77fc2a9fd)

**Comment by Levsha-Sl** [comment]
Надо заменять буквы А и О

**Comment by Levin-crk** [comment]
Так а есть рабочий код , данной программы ?

**Comment by Levsha-Sl** [comment]
Сделал изменить в скрипте все снова работает) дело в алфавите

**Comment by Friendly595** [comment]
> Сделал изменить в скрипте все снова работает) дело в алфавите

Поделитесь фиксом, срочно необходим?

**Comment by Levsha-Sl** [comment]
> > Сделал изменить в скрипте все снова работает) дело в алфавите
> 
> Поделитесь фиксом, срочно необходим?

@Friendly595 Дайте немного времени я был не на своем устройстве, сейчас зайду через свой ноут и все сделаю.

**Comment by Levin-crk** [comment]
ожидаю , заранее спасибо за фикс

**Comment by Levsha-Sl** [comment]
@Friendly595 @Levin-crk
Фикс можете взять тут, пока владелец не одобрил его у себя) 
https://github.com/Levsha-Sl/nmocrasher

**Comment by Levin-crk** [comment]
> @Friendly595 @Levin-crk
> 
> Фикс можете взять тут, пока владелец не одобрил его у себя) 
> 
> https://github.com/Levsha-Sl/nmocrasher

Спасибо , там все автоматом работает ?

**Comment by Levsha-Sl** [comment]
> Спасибо , там все автоматом работает ?

Да, за исключением тех вопросов в которых есть Английские слова, в общем пару вопросов пропустить может, но это минимум.

**Comment by Friendly595** [comment]
> > @Friendly595 @Levin-crk
> > Фикс можете взять тут, пока владелец не одобрил его у себя)
> > https://github.com/Levsha-Sl/nmocrasher
> 
> Спасибо , там все автоматом работает ?

Спасибо.

**Comment by Levsha-Sl** [comment]
@Friendly595 @Levin-crk 
сделал ещё один фикс, сейчас все работает на моем устройстве. Попробуйте снова поставить мой код. Напишите пожалуйста свой отзыв. У вас все в порядке?

**Comment by Kostym4iks** [comment]
Да последний фикс помог 
Спасибо

**Comment by Friendly595** [comment]
Щас у всех вариант не открывает?

**Comment by Levsha-Sl** [comment]
> Щас у всех вариант не открывает?

Я знаю что нужно уменьшать окно сайта, до того момента как появиться кнопка "свернуть-развернуть". Развернуть заголовок и тогда скрипт начнет работать. В ином случае поиск темы не начинался.

**Comment by Friendly595** [comment]
> > Щас у всех вариант не открывает?
> 
> Я знаю что нужно уменьшать окно сайта, до того момента как появиться кнопка "свернуть-развернуть". Развернуть заголовок и тогда скрипт начнет работать. В ином случае поиск темы не начинался.

Имею ввиду сайт не работает, не открывает тест.
