### ISSUE TITLE
Что делать , если ответы загружены , но не вставлются?

### ISSUE THREAD

**Issue by Levin-crk** [kiray-gd/nmocrasher#5]

**Comment by Levin-crk** [comment]
помогите пожалуйста решить вопрос

**Comment by Levsha-Sl** [comment]
Здравствуйте, решил вопрос, дело в алфавите

**Comment by Levsha-Sl** [comment]
Тут обсуждение того же вопроса 
https://github.com/kiray-gd/nmocrasher/issues/4

**Comment by kiray-gd** [comment]
Решено. Принял изменения и модифицировал их для всех возможных вариантов похожих букв, а также, чтобы исправлялись только одиночно расположенные буквы и буквы в "кириллических" словах.
