### ISSUE TITLE
Привет, новая защита(

### ISSUE THREAD

**Issue by Melni62** [kiray-gd/nmocrasher#8]
Как я понял добавили курсив в буквах и шрифт  к, о, в. А также цифр

**Comment by MaximMedik** [comment]
![20240823_180052](https://github.com/user-attachments/assets/35e2b359-5a8a-4ab7-bb43-5338c8707724)
Ага, буквы скачут....снова извращаются

**Comment by MaximMedik** [comment]
![20240823_180052](https://github.com/user-attachments/assets/36eda9de-58d9-495a-b52e-b5ec69ae9008)
Ага...буквы скачут.....
Вопрос риторический, но зачем они сопротивляются.....зачем?....

**Comment by Melni62** [comment]
Что то мне кажется что скоро они будут вместо вопросов, картинку вставлять xD что-бы ничего сделать нельзя было

**Comment by MaximMedik** [comment]
> Что то мне кажется что скоро они будут вместо вопросов, картинку вставлять xD что-бы ничего сделать нельзя было

Делать скриншот каждого вопроса? 😅

**Comment by TemPoun** [comment]
у вас тоже скипает все вопросы?

**Comment by Melni62** [comment]
Да. Жалко что сайт не работает, я бы тоже попробовал поправить(

**Comment by MaximMedik** [comment]
> у вас тоже скипает все вопросы?

Да

**Comment by Friendly595** [comment]
> у вас тоже скипает все вопросы?

Сегодня вышла новая защита, если они только поработали над символами, то это тоже обходится.

**Comment by Melni62** [comment]
самое что интересное, латинскую защиту они удалили и добавили другую xD

**Comment by Friendly595** [comment]
> самое что интересное, латинскую защиту они удалили и добавили другую xD

Странные решения, но я думаю, что они тоже читают все эти ответы)

**Comment by TemPoun** [comment]
Я надеюсь это возможно исправить?

**Comment by Friendly595** [comment]
> Я надеюсь это возможно исправить?

Возможно конечно.

**Comment by Melni62** [comment]
> > Я надеюсь это возможно исправить?
> 
> Возможно конечно.

Это исправляется сложнее чем было, потому что мне кажется там не только шрифт поменялся, мне кажется курсивы в буквах тоже, но это исправляется

**Comment by TemPoun** [comment]
Они если видят все эти сообщения ,то дальше будет невозможно

**Comment by Melni62** [comment]
Я думаю очень вряд-ли, потому что всё таки и 30 человек не наберётся кто программой пользуется, но всё возможно)

**Comment by TemPoun** [comment]
Это они эту защиту поставили спустя сколько после  фикса

**Comment by Friendly595** [comment]
> Это они эту защиту поставили спустя сколько после фикса

Спустя пару часов.

**Comment by TemPoun** [comment]
И как быть дальше? они же все будут дефать

**Comment by Friendly595** [comment]
> И как быть дальше? они же все будут дефать

Здесь тоже люди знающие сидят, поэтому пусть.

**Comment by Melni62** [comment]
Мне кажется они поменяли так быстро потому что они когда тесты добавляют у них ошибки происходят потому что буквы на латиницы некоторые, а щас они сделали другой шрифт что бы легче было, потому что не вижу смысла удалять старую защиту, добавляя новую))

**Comment by TemPoun** [comment]
Они если это исправили,значит они видят наши сообщения

**Comment by TemPoun** [comment]
так бы им дело небыло до этого

**Comment by Friendly595** [comment]
> Мне кажется они поменяли так быстро потому что они когда тесты добавляют у них ошибки происходят потому что буквы на латиницы некоторые, а щас они сделали другой шрифт что бы легче было, потому что не вижу смысла удалять старую защиту, добавляя новую))

Совмещая свои защиты, они себе проблемы делают, тут другой подход нужен, нам же проще с этим работать.

**Comment by Melni62** [comment]
ну за то теперь будут проходиться тесты где на английском ответы ))) надо искать плюсы

**Comment by MaximMedik** [comment]
Я готов задонатить даже.....у врачам нас 60-70 лет, какие тесты в самом деле, эта штука хоть как то облегчает помощь для них , нам задали по 135 штук сделать по специальности....

**Comment by Melni62** [comment]
у меня 12 окон с этой программой xD, делают программу

**Comment by Friendly595** [comment]
> Я готов задонатить даже.....у врачам нас 60-70 лет, какие тесты в самом деле, эта штука хоть как то облегчает помощь для них , нам задали по 135 штук сделать по специальности....

А раньше даже и ответов не было, приходилось изучать материалы.

**Comment by TemPoun** [comment]
Они это видят,они же не глупцы

**Comment by TemPoun** [comment]
Ладно пофиксим

**Comment by MaximMedik** [comment]
> Они это видят,они же не глупцы
Есть у меня теория, что они помогают фирмам, которые много денег берут за решение тестов

**Comment by Melni62** [comment]
на сайте 120 посещений за месяц, шансы крайне малы), а ваще такой фигнёй должны заниматься 24forcare.com потому что они заинтересованное лицо что бы их сайт посещали

**Comment by TemPoun** [comment]
Да,в интернете 1 иом стоит 500 рублей)

**Comment by Melni62** [comment]
сколько сколько?

> Да,в интернете 1 иом стоит 500 рублей)

**Comment by TemPoun** [comment]
500

**Comment by Melni62** [comment]
я за 30 рублей 1 иом делаю xDDDDDD

**Comment by TemPoun** [comment]
Мне бы ходябы сделать свою норму

**Comment by Melni62** [comment]
у меня тоже заявки в простое(, слава богу что выходные, можно пофиксить

**Comment by Melni62** [comment]
У вас сайт тесты грузят?

**Comment by Friendly595** [comment]
> У вас сайт тесты грузят?

Нет, ждем.

**Comment by TemPoun** [comment]
Ошибку выдает

**Comment by TemPoun** [comment]
Если я хочу итоговый тест получить новый вариант

**Comment by Melni62** [comment]
надо телеграмм канал автору создать))

**Comment by MaximMedik** [comment]
> я за 30 рублей 1 иом делаю xDDDDDD

Я своим по божески 15р

**Comment by TemPoun** [comment]
надо

**Comment by Melni62** [comment]
> > я за 30 рублей 1 иом делаю xDDDDDD
> 
> Я своим по божески 15р

Да я тоже за всё берусь, мне приходило предложение делать 10к баллов за ОДНУ неделю по цене....3рубля за балл, я решил что здоровье важнее )0

**Comment by Friendly595** [comment]
> > > я за 30 рублей 1 иом делаю xDDDDDD
> > 
> > 
> > Я своим по божески 15р
> 
> Да я тоже за всё берусь, мне приходило предложение делать 10к баллов за ОДНУ неделю по цене....3рубля за балл, я решил что здоровье важнее )0

Мне бы твой заказ, я бы вязл :D

**Comment by TemPoun** [comment]
xD

**Comment by Melni62** [comment]
> > > > я за 30 рублей 1 иом делаю xDDDDDD
> > > 
> > > 
> > > Я своим по божески 15р
> > 
> > 
> > Да я тоже за всё берусь, мне приходило предложение делать 10к баллов за ОДНУ неделю по цене....3рубля за балл, я решил что здоровье важнее )0
> 
> Мне бы твой заказ, я бы вязл :D

Я просто посчитал, что мне потребуется по 12 часов в день фигачить 7 дней в неделю что бы просто успеть xD и это я брал в расчёт если все тесты будут по 3 балла

**Comment by Melni62** [comment]
сайт заработал)

**Comment by Friendly595** [comment]
> > > > > я за 30 рублей 1 иом делаю xDDDDDD
> > > > 
> > > > 
> > > > Я своим по божески 15р
> > > 
> > > 
> > > Да я тоже за всё берусь, мне приходило предложение делать 10к баллов за ОДНУ неделю по цене....3рубля за балл, я решил что здоровье важнее )0
> > 
> > 
> > Мне бы твой заказ, я бы вязл :D
> 
> Я просто посчитал, что мне потребуется по 12 часов в день фигачить 7 дней в неделю что бы просто успеть xD и это я брал в расчёт если все тесты будут по 3 балла

Это же все тоже автоматизируется, правда сил нужно побольше)

**Comment by Melni62** [comment]
удалили защиту
аахахахаххаха

**Comment by TemPoun** [comment]
Лол почему

**Comment by MaximMedik** [comment]
> удалили защиту аахахахаххаха

Может придумывают чего по изощреннее

**Comment by Melni62** [comment]
> > > > > > я за 30 рублей 1 иом делаю xDDDDDD
> > > > > 
> > > > > 
> > > > > Я своим по божески 15р
> > > > 
> > > > 
> > > > Да я тоже за всё берусь, мне приходило предложение делать 10к баллов за ОДНУ неделю по цене....3рубля за балл, я решил что здоровье важнее )0
> > > 
> > > 
> > > Мне бы твой заказ, я бы вязл :D
> > 
> > 
> > Я просто посчитал, что мне потребуется по 12 часов в день фигачить 7 дней в неделю что бы просто успеть xD и это я брал в расчёт если все тесты будут по 3 балла
> 
> Это же все тоже автоматизируется, правда сил нужно побольше)

я пробовал автоматизировать с помощью макросов, но сайт настолько плох что кнопки уезжают из-за рамера текста

**Comment by Melni62** [comment]
не ну они точно нас читают, щас реально пнг картинки будут, ждём короче)0

**Comment by TemPoun** [comment]
ахахаха

**Comment by Melni62** [comment]
ну либо они опять из-за защиты сломали всё

**Comment by Friendly595** [comment]
> не ну они точно нас читают, щас реально пнг картинки будут, ждём короче)0

Это анреал, никто этим заниматься не будет, да и в целом на этот счет тоже есть решение.

**Comment by Melni62** [comment]
ну картинку нельзя обойти, только системой которая считывает текст, но за программировать не получиться

**Comment by TemPoun** [comment]
Я думаю что они щас сделают что-то невозможное

**Comment by Melni62** [comment]
короче надо ждать ночью обновления ULTRA DEFENCE V3.0

**Comment by TemPoun** [comment]
ахахха дададад

**Comment by Melni62** [comment]
Не, ну раз защиты нет закрываю дисскусию, спасибо что сидели хаахха, увидимся ночью возможно()) либо через час

**Comment by Boris20A** [comment]
Сегодня в о-30 утра были технические работы и после них перестали ответы вставляться

**Comment by Boris20A** [comment]
У кого работает?

**Comment by Boris20A** [comment]
работает?
